### PR TITLE
Better waiting mechanism to check for DNS updates

### PR DESCRIPTION
**Pull request by antoninkriz**
This should be faster and more solid way of checking if the DNS is already updated or not instead of just waiting for preset amount of time.

### CODE REVIEW

**Comment by Ashus** [comment]
Have you tested this?
Good idea, but I'll take care of fixing it.

**Comment by antoninkriz** [comment]
I did. Works fine, but
```php
$dns = dns_get_record('_acme-challenge' + CERTBOT_DOMAIN, DNS_TXT);
```
has to be changed to
```php
$dns = dns_get_record('_acme-challenge' . CERTBOT_DOMAIN, DNS_TXT);
```

**Comment by Ashus** [comment]
I believe it hit the timeout, because even with this fix, the dns_get_record must have resulted in failure without dot before domain name. I was asking because there is lot of DNS caching around and even PHP might possibly cache the result on its own.
Nevermind, I fixed it, optimized it and tested it successfully. The timeout will have to be increased even more.

**Comment by antoninkriz** [comment]
Awesome. Thank you

**Pull request merged**
